name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: the-human-colossus-foundation/oca-spec
        TARGET_BRANCH: pages
        BUILD_SCRIPT: npm i && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: oca.colossi.network
